// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// relative_diff
arma::mat relative_diff(const arma::sp_mat& M);
RcppExport SEXP _mclink_relative_diff(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(relative_diff(M));
    return rcpp_result_gen;
END_RCPP
}
// mc_sample_matrix
arma::sp_mat mc_sample_matrix(const arma::sp_mat& M, const size_t sample_size, const int min_distance);
RcppExport SEXP _mclink_mc_sample_matrix(SEXP MSEXP, SEXP sample_sizeSEXP, SEXP min_distanceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const size_t >::type sample_size(sample_sizeSEXP);
    Rcpp::traits::input_parameter< const int >::type min_distance(min_distanceSEXP);
    rcpp_result_gen = Rcpp::wrap(mc_sample_matrix(M, sample_size, min_distance));
    return rcpp_result_gen;
END_RCPP
}
// shuffle_sparse_rows
arma::sp_mat shuffle_sparse_rows(const arma::sp_mat& M);
RcppExport SEXP _mclink_shuffle_sparse_rows(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(shuffle_sparse_rows(M));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mclink_relative_diff", (DL_FUNC) &_mclink_relative_diff, 1},
    {"_mclink_mc_sample_matrix", (DL_FUNC) &_mclink_mc_sample_matrix, 3},
    {"_mclink_shuffle_sparse_rows", (DL_FUNC) &_mclink_shuffle_sparse_rows, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_mclink(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
